backend:
  name: github
  repo: autopoet/my-blog
  branch: master # 如果你的 GitHub 分支是 main，请改为 main
  base_url: https://my-blog-puce-one.vercel.app/ # 指向你的网站根目录
  auth_endpoint: api/auth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "博文管理"
    folder: "pages/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "分类", name: "categories", widget: "list", default: ["面试八股"] }
      - { label: "标签", name: "tags", widget: "list" }
      - { label: "内容", name: "body", widget: "markdown" }
